### ISSUE TITLE
error 10054

### ISSUE THREAD

**Issue by Eddyxuu** [XiaoJiang0208/TarkovMapTool#5]
Traceback (most recent call last):
  File "C:\00_ProSoftware\anaconda3\envs\sussex\lib\site-packages\selenium\webdriver\common\driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "C:\00_ProSoftware\anaconda3\envs\sussex\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 106, in driver_location
    output = self.run(args)
  File "C:\00_ProSoftware\anaconda3\envs\sussex\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 154, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}.\n{result}{stderr}")
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: C:\00_ProSoftware\anaconda3\envs\sussex\lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser MicrosoftEdge --language-binding python --output json.
{'code': 65, 'message': 'error sending request for url (https://msedgedriver.azureedge.net/LATEST_RELEASE_121_WINDOWS): error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)', 'driver_path': '', 'browser_path': ''}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\eddyx\Downloads\TarkovMapTool-maptool-1.0\TarkovMapTool-maptool-1.0\TKFtool.py", line 122, in <module>
    driver = webdriver.Edge()
  File "C:\00_ProSoftware\anaconda3\envs\sussex\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\00_ProSoftware\anaconda3\envs\sussex\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
  File "C:\00_ProSoftware\anaconda3\envs\sussex\lib\site-packages\selenium\webdriver\common\driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

**Comment by Eddyxuu** [comment]
本质为没有所属对应Edge版本的selenium驱动
下载selenium最新的驱动，将驱动文件放置于Edge文件夹中，并将Edge目录添加环境变量即可解决
